### ISSUE TITLE
General Improvements for gene identification and network browsing

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#17]
## Description

When a gene is identified, useful info about it include its name and its neighbors. The interface to this information should be easy to retrieve and to identify. For instance, when a gene is clicked, the gene is highlighted in the network and in the table. Additionally the neighbors are highlighted, but only in the network. The useful bits of information should be easily relate-able between the table and the graph.  The use case we are targeting here is somebody loading a network generated from GWAS and then identifying the subnetwork that is biologically relevant to them:

> Sally is interested in iron. She knows iron is taken up in the roots so she selects the ZmRoot network and the ZmIonome dataset focusing on Fe57. Once the network is loaded, she sorts the gene table by degree, trying to identify hubs. She clicks the top three genes in the table, which are highlighted directly in the network. Included in the network, are 54 next neighbors. Sally notices that there are known transporter genes for other elemental metals in this list. She also notices that using the top three genes in the network, she can cover over half of the SNPs. This makes Sally happy. Sally tells all her friends and colleagues about COB. Sally orders a victory pizza :pizza:  
## Tasks
- [x] Add bread crumbs somewhere on the page (footer?) that shows loaded network/GWAS combo
  - e.g.: **ZmIonome > ZmRoot > Fe57**
- [ ] Highlight clicked gene neighbors in the table
### Gene Labeling improvement
- [x] Include informative tool tips for genes
  - [x] Gene name
  - [x] Chromosomal Location
  - [ ] Common gene name (this can either be a hack or we can talk about adding an annotation class to the current RefGen class.
- [x] Include tool tips for SNP groups
  - [x] List of Included SNPs
  - [x] Chromosome Location 
### Table Improvements
- [x] Remove of locality in the table
- [ ] Add gene specific density to table
- [x] Add WindowSize and FlankLimits to parameters tab
### More complex clicking login

We generally want to avoid losing highlighted nodes by accident
- [x] Add a toggle in the parameters tab for more subtle clicking logic:
- [x] Nodes should be un-highlighted through a second click
- [x] Neighbors should only be unhighlighted if they are not connected to another clicked gene
- [x] Add a _clear all_ button somewhere that un-highlights everything.

**Comment by monprin** [comment]
1. Would it still be okay to put the subnetwork in its own table on another tab rather than trying to just highlighting them in the main one, as that table can get rather long.
2.  I'll get the tooltip stuff working in general before worrying about how to do the common name.
3. I don't know what gene specific density is.
4. Can the new click logic be more or less summed up as: 'Flip the functionality of the ctrl key, and add a toggle'?

**Comment by schae234** [comment]
1. Yes, having another table with the local genes would be fine. In another tab maybe?
2. Tool tips look great. Common names will be covered in another Issue
3. Don't worry about this either, I think we can handle extraneous info in another Issue (same as above)
4. The logic would be: "click once to highlight, click again to un-highlight". Maybe just forget about the toggle, since each gene will essentially be a toggle.

**Comment by monprin** [comment]
With #19 I think we can close this, I am going to do the subnetwork gene table, but that is not really within the purview of this anymore.

**Comment by schae234** [comment]
Agreed, I will check out #19 and come up with another round of iteration for use cases.
