### ISSUE TITLE
Iteration #3

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#23]
## Tasks for Joe to do
- [x] Sort grouped SNPs by their highest gene's local degree
- [x] Also highlight clicked genes in subnetwork table
- [x] add gene count to breadcrumbs (updates after filtering)
- [x] Query the network using a list of genes instead of a term
- [ ] parent attrs
- [x] exporting gene tables
  - [x] include network parameters
## Gene annotation
- [ ] TBD

**Comment by monprin** [comment]
Been Addressed by other issues
