### ISSUE TITLE
Advanced network query system

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#27]
Provide an alternative to networks built from the Ontology based gene mapping, similar to functionality at http://csbio.cs.umn.edu/cob. 

Allow for a list of genes to be provided and build a network from these. This will also include **all first neighbors** of query genes. Include interactions among neighbors also. 

We will implement this instead of the second network that includes all global genes. If you wanted to see the local / global neighbors of a gene, you can use this instead.
## Tasks
- [x] Generate network from genes in query box
- [x] Include first neighbors of all query genes
- [x] Apply force directed layout instead of polywas layout
- [x] Color query nodes different from neighbor nodes
- [x] Default to 0 degree filter (I want to see if queries are not connected to anything)
- [x] Disable parameter boxes for FlankLimit and WindowSize
- [x] Add Example gene/query to text box
- [x] Map aliaes to GRMZM names, include aliases in the gene table.
- [x] Implement original COB top neighbors algorithm (below)
- [x] Add ability to load unrendered nodes with click
- [x] Add gene name tool tip in search box for both GRMZM names as well as aliases
- [x] Allow for querying of Ontology term names. e.g. GO:000014 will load all genes associated with that GO term

**Comment by monprin** [comment]
If you have time, could you maybe give me a quick example use case so I can get an idea of the work flow?

**Comment by schae234** [comment]
Sure.

> Vlad cares about getting big and strong. He wants to make sure that he is getting enough vitamin A so he can one day be strong enough to overpower his enemies. Vlad is working on a secret project to increase the amount of vitamin A in his favorite power food, Maize. He has a list of genes that he generated using super secret experiments that he thinks control Vitamin A levels in maize grain. Vlad heard about using co-expression to validate whether or not lists of genes maybe be functionally related. He downloads and install cob so he can see any interactions. He doesn't see vitamin A on any of the pre-loaded ontologies so he opts to use the custom search feature in cob. He enters his list of genes into the query box on COB and generates a network. The network contains all the genes in his list but also any other genes that connect to two or more of his query set. He sees that there are quite a few direct interactions between his original gene set, but to his surprise, he discovers a couple new genes that are highly connected to his original query set. In fact, without these key hubs, his original set does not look like it would be that interesting at all. These could be interesting new candidates to explore! Maybe they are master vitamin A regulators! Jackpot! :moneybag:  Using this information, Vlad adds those extra couple of genes to his Vitamin A list using co-expression as evidence of related Vitamin A function. Vlad is happy. He celebrates by cooking an extra large steak for dinner. :cow2:

**Comment by monprin** [comment]
New tasks now that I have a version working reasonably well!
- [x] Report genes that do not appear in the selected network
- [x] Tailor gene tables to current graph - will be done in conjunction with gene annotation system, removing from this issue.

**Comment by monprin** [comment]
#38 Adds this! With the possible exception of the table optimizations

**Comment by schae234** [comment]
Per your gchat and talking to Meesh, lets implement the following algorithm for loading a sane number of neighbors (Its the one we used in the original COB website):
- Generate a subnetwork of query genes including neighbors
- Calculate local degree for all genes
- Render all query genes and top X neighbors (default: 50)
- Report **all** genes in the table 
  - Include a "Rendered" column in the table
  - If table row for unrendered gene is clicked, render and add it to the network

Does this sound feasible? It will add some pretty complex logic but is an implementation that I've been wanting for a long long time.

**Comment by schae234** [comment]
Another thing the original COB implemented for advanced querying is using aliases. Can your query system also search an alias list and map the GRMZM number, the list is here:

http://ftp.maizesequence.org/release-5b/named-genes/ZmB73_5a_named_genes.txt

Can you include aliases in the gene table and tool tip?

**Comment by monprin** [comment]
For aliases, since that is implemented into refgen in camoco, shouldn't we just piggyback off that so the code is only in one place?

**Comment by schae234** [comment]
Yes, I forgot about that. Use the code from RefGen for sure!

**Comment by schae234** [comment]
I added some super advancements to the tasks list above.

**Comment by monprin** [comment]
Okay so working on the algorithm I cam up with an issues, when I query the 4 default genes and retain all of the neighbors, I end up with 897 neighbors and 152,195 edges, which takes forever to pack up and process, how did you deal with this in your implementation? Basically there are some nodes that just have 800 neighbors, who then will just also inevitably be connected to other neighbors, so it balloons the edges count on the scale of n^2 , it just straight up crashes the browser page.

**Comment by monprin** [comment]
New general paradigm as reminder from chat:

Have one request to get the top X genes and edges and build the graph from that, have a second server channel to just get the name of all of the genes that are connected and populate the table with that.

With that working, update click logic to update the graph by issuing a request to the server to pull that gene and its connections to genes already in the graph and re-render, do not run a whole new query.

**Comment by monprin** [comment]
Done except for ontology queries which will get its own issue, in next PR.

**Comment by monprin** [comment]
What will happen is done in #50
