### ISSUE TITLE
Filter genes based on X

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#4]
## Description

Due to faulty SNP to gene mapping, there is often many genes that do not have any edges and are very likely noise. We want to be able to filter out genes based on basic criteria

![screenshot from 2016-05-17 11 34 05](https://cloud.githubusercontent.com/assets/2566591/15330622/4de2ad32-1c23-11e6-8459-917d1dfff356.png)
## Tasks
- [x] Add basic filters to graph
  - [x] Filter nodes on minimum degree
  - [x] Filter edges on minimum score
## Notes

See [here](https://github.com/schae234/Camoco/blob/31155cd232dd05dbc79e3c3a577470cf676ba2ce/interfaces/static/js/cob.js#L115-L132) for some hints. Cytoscape.js is weird, even when you delete nodes, it keeps them, just doesnt display them. Filtering is basically two steps, 1) bringing everything back then 2) applying a filter based on the criteria. [Here](https://github.com/schae234/Camoco/blob/31155cd232dd05dbc79e3c3a577470cf676ba2ce/interfaces/static/js/cob.js#L35-L55) there are two HTML fields that fire events when they are changed and the new filters were applied using the code above.

**Comment by monprin** [comment]
Functional in most recent version of my repo, though waiting until there is a better interface before making a pull request and officially closing this.

**Comment by schae234** [comment]
This works great. The interface change would be great. We could have a tab that is for options/parameters. Once it is there, I think we can call this one closed.

**Comment by monprin** [comment]
Added in #12. Interface may get tweaked, and more parameters may get added, but it works.

**Comment by monprin** [comment]
Added in #12. Interface may get tweaked, and more parameters may get added, but it works.
