### ISSUE TITLE
Gene clicking logic

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#5]
## Description

Genes should have some handy logic when they are clicked. This makes it easier to identify who a gene is and also who it interacts with. 
## Tasks
- [x] Highlight a node when it is clicked, the node should be in the class 'selected'
- [x] When a node is clicked and already 'selected' highlight and select its neighbors
- [x] Allow ctrl+click to group genes
- [x] When gene info table is added (will open issue on this) highlight entry in gene table when a gene is clicked
## Notes

Some of these features were also partially implemented [here](https://github.com/schae234/Camoco/blob/31155cd232dd05dbc79e3c3a577470cf676ba2ce/interfaces/static/js/cob.js#L393-L445)

**Comment by monprin** [comment]
Can you clarify task 3?

**Comment by schae234** [comment]
Make it so holding ctrl will ensure that currently selected nodes do not lose focus. 

This is especially annoying when you accidentally click outside of a node and lose all your selected genes. We might want to add a 'sticky' option or some sort of smarter logic for selecting multiple nodes later or something.

**Comment by monprin** [comment]
Implemented, with proper deselection, in #16.
