### ISSUE TITLE
Gene info table

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#6]
## Description

While the network is great for looking at interactions, it is not so good at showing info about genes. Add a gene info table that prints information based off of `refgen.candidate_genes()` called [here](https://github.com/schae234/cob/blob/a50eaa13189b21e308317cc76bc286450c7a3ac7/COB.py#L82). Include all the information from the `include_xxx` kwargs [here](https://github.com/schae234/Camoco/blob/2a30a83935e686771b06083179b4aea5435a6680/camoco/RefGen.py#L391-L415).
## Tasks
- [x] Add a gene data table
- [x] Link the gene table with the network:
  - [x] highlight nodes when rows are clicked
  - [x] highlight rows when nodes are clicked

**Comment by monprin** [comment]
This one is resolved in #13, this can be closed once that is merged.

**Comment by schae234** [comment]
Before we close this can you include the information from the optional `include_xxx` kwargs in `refgen.candidate_genes()`? I think you should be able to just set them all to True.

**Comment by monprin** [comment]
#16 has most of them included, waiting on Camoco fixes for the others, but once they are there, the code is in here, it just needs to be uncommented when ready.
